ALTER TABLE ventas
    ADD COLUMN iva DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER descuento,
    ADD COLUMN domicilio DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER iva,
    ADD COLUMN empaque DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER domicilio;
